#!/bin/sh
lan_address="`cat /sys/class/net/eth0.1/address`"
wan_address="`cat /sys/class/net/eth0.2/address`"

cat << EOF > /etc/config/network

config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config interface 'wan_controller'
        option ifname 'eth0.5'
        option proto 'dhcp'

config device 'wan_dev'
        option name 'eth0.5'
        option macaddr \'$wan_address\'

config interface 'lan1'
        option ifname 'eth0.1'
        option proto 'static'

config interface 'lan2'
        option ifname 'eth0.2'
        option proto 'static'

config interface 'lan3'
        option ifname 'eth0.3'
        option proto 'static'

config interface 'lan4'
        option ifname 'eth0.4'
        option proto 'static'

config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '4'
        option ports '0 6t'

config switch_vlan
        option device 'switch0'
        option vlan '3'
        option ports '1 6t'

config switch_vlan
        option device 'switch0'
        option vlan '2'
        option ports '2 6t'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '3 6t'

config switch_vlan
        option device 'switch0'
        option vlan '5'
        option ports '4 6t'

EOF

cat << EOF > /etc/config/wireless
config wifi-device 'radio0'
        option type 'mac80211'
        option channel '11'
        option hwmode '11g'
        option path 'pci0000:00/0000:00:01.0/0000:02:00.0'
        option htmode 'HT20'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option mode 'ap'
        option ssid '$HOSTNAME'
        option encryption 'none'
        option ifname wlan0

config wifi-device 'radio1'
        option type 'mac80211'
        option channel '36'
        option hwmode '11a'
        option path 'pci0000:00/0000:00:00.0/0000:01:00.0'
        option htmode 'VHT80'

config wifi-iface 'default_radio1'
        option device 'radio1'
        option mode 'ap'
        option ssid '$HOSTNAME_5G'
        option encryption 'none'
        option ifname wlan1

EOF